### ISSUE TITLE
[FEATURE] 리팩토링

### ISSUE THREAD

**Issue by yj-leez** [team-acode/acode-server#34]
## Description
코드 리팩토링 및 클린 코드 준수 진행 중입니다.
## Todo
- [x] 테스트 코드 작성 및 테스트용 환경 설정 완료
- [x] 동시성 처리
- [x] 예외 처리 자세하게 추가하며 함수 분리
- [ ] 그 외 클린 코드 진행
## ETC
기타 사항

**Comment by yj-leez** [comment]
예외 처리 수정 흐름은 해당 링크 아래 쪽에 작성해두었습니다! https://github.com/yj-leez/BackEnd-WIL/blob/main/CleanCode/Ch7.md

**Comment by yj-leez** [comment]
테스트용 데이터베이스 환경 설정은 해당 링크 하단에 작성해두었습니다! https://github.com/yj-leez/BackEnd-WIL/blob/main/CleanCode/Ch9.md
