### ISSUE TITLE
[FEATURE] 리팩토링

### ISSUE THREAD

**Issue by yoonsseo** [team-acode/acode-server#36]
## Description
설명을 작성하세요.
## Todo
- [ ] sout -> log로 변경
- [ ] review update 엔티티 내 비즈니스 로직으로 변경
- [ ] 주석 처리해둔 코드 삭제
## ETC
기타 사항
